toolbar:
  - styleselect | bold italic underline | align | undo redo | link | table | numlist bullist | searchreplace spellchecker
plugins:
  - table
  - link
  - lists
  - advlist
  - searchreplace
  - spellchecker
  